version: "3.9"

services:
  roma:
    build:
      context: .
      dockerfile: Dockerfile.roma
    container_name: petsiq-roma
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8001/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: petsiq-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PORT=8000
      - ROMA_HOST=roma
      - ROMA_PORT=8001
    depends_on:
      roma:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped